import type { Metadata } from "next";
import { Krub } from "next/font/google";
import "./globals.scss";

const krubFont = Krub({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${krubFont.className}`}>{children}</body>
    </html>
  );
}
